# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "SLES12"
  # config.vm.synced_folder "../data", "/vagrant_data"
  #
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL

  config.vm.provision 'shell', path: './scripts/webserver.sh'
end
